 # ---- Training ----
  batch_size:
    values: [512, 256, 128]

  lr:
    values: [0.001, 0.0001, 0.00001]

  optimizer:
    values: [Adam, AdamW, SGD]

  finetune_layers:
    values: [1, 3, 5]

  sheaf_layers:
    values: [1, 3, 5]

  alpha:
    values: [1, 1.2, 1.5]

  weights_components:
    values: [1, 0.7, 0.5, 0.3, 0]

  weights_kl_vs_clip:
    values: [1, 0.7, 0.5, 0.3, 0] 

  w_clip_vs_mask:
    values: [1, 0, 0.5, 0.3, 0.7] 
  test:
    values: [False, True]
    
  out_proj: 
    values: [False, True]

  _laplacian_heat_kernel:
    values: [False, True]

