 # ---- Training ----
  batch_size:
    values: [512, 256, 61284]

  lr:
    values: [0.001, 0.0001, 0.00001]

  optimizer:
    values: [adamw, sgd]

  # ---- Model dimensions ----
  latent_dim:
    values: [512, 256]

  finetune_layers:
    values: [2, 4, 6]

  sheaf_layers:
    values: [2, 3, 4]

  alpha:
    values: [1.2, 1.7, 1.8]

  
  weights_components:
    values:
      - [0.7, 0.5, 0.3]

  weights_kl_vs_clip:
    values: [0.7, 0.5, 0.3]

  w_clip_vs_mask:
    values: [0.7, 0.5, 0.3]

